### ISSUE TITLE
User feedback on switch

### ISSUE THREAD

**Issue by yannickwurm** [yeban/oswitch#6]
Should add a colourful message on successful switch
```
************************
* You are now running: “ Whatevs whatevs. "
& give quick list of mounted dirs.
************************
```
Otherwise all I see is the failed zsh commands (chruby not loading etc)

**Comment by yeban** [comment]
Relevant - ce3c701639156f406e4679cf77fd3d8568f16c74. Just I can't preserve newlines on print.

**Comment by yeban** [comment]
Broke after #12.
